submitter: Principal DevOps engineer
themes: # rated 1-5
  availability_and_capacity_management: 4
  development_process_optimisation: 5
  development_process_optimisation_management: 1
  information_security: 5
  modern_standards_approach: 5
  programming_and_build_software_engineering: 4
  prototyping: 5
  service_support: 5
  systems_design: 4
  systems_integration: 5
  user_focus: 4
