submitter: Trainee data scientist
themes: # rated 1-5
  applied_maths,_statistics_and_scientific_practices: 2
  data_engineering_and_manipulation: 2
  data_science_innovation: 2
  delivering_business_impact: 2
  developing_data_science_capability: 2
  ethics_and_privacy_data_science: 2
  programming_and_build_data_science: 2
  understanding_product_delivery: 2
