submitter: Application operations engineer
themes: # rated 1-5
  asset_and_configuration_management: 3
  availability_and_capacity_management: 3
  change_management: 2
  continual_service_improvement: 2
  incident_management: 2
  ownership_and_initiative: 3
  problem_management: 2
  service_focus: 3
  service_management_framework_knowledge: 2
  technical_specialism: 2
  technical_understanding: 2
  testing: 2
  user_focus: 3
