submitter: Principal application operations engineer
themes: # rated 1-5
  asset_and_configuration_management: 4
  availability_and_capacity_management: 4
  change_management: 4
  continual_service_improvement: 4
  incident_management: 4
  ownership_and_initiative: 4
  problem_management: 4
  service_focus: 4
  service_management_framework_knowledge: 4
  technical_specialism: 5
  technical_understanding: 4
  testing: 5
  user_focus: 4
