submitter: Trainee business analyst
themes: # rated 1-5
  agile_working: 2
  business_analysis: 2
  business_modelling: 1
  business_process_improvement: 2
  business_process_testing: 2
  consultancy_business_analysis: 1
  enterprise_and_business_architecture_business_analyst: 1
  methods_and_tools: 1
  requirements_definition_and_management: 2
  stakeholder_relationship_management_business_analysis: 2
  systems_analysis: 2
  testing_business_analysis: 2
  user_experience_analysis: 1
