submitter: Configuration analyst
themes: # rated 1-5
  asset_and_configuration_management: 3
  availability_and_capacity_management: 2
  change_management: 2
  community_collaboration: 3
  continual_service_improvement: 2
  continuity_management: 2
  incident_management: 2
  ownership_and_initiative: 2
  problem_management: 2
  service_focus: 2
  service_management_framework_knowledge: 2
  technical_understanding: 2
  user_focus: 2
